title: Landing Zone
description: Landing Zone developed by OCI RSA
schemaVersion: 1.1.0
version: "0.1"
locale: en
variableGroups:
  - title: Provider Variables
    visible: false
    variables:
      - api_fingerprint
      - api_private_key_path
      - region
      - tenancy_ocid
      - current_user_ocid
  - title: Tagging
    variables:
      - tag_cost_center
      - tag_geo_location
  - title: Compartment
    variables:
      - parent_compartment_name
      - workload_compartment_names
      - show_extra_compartment_names
      - network_compartment_name
      - security_compartment_name
      - common_infra_compartment_name
      - applications_compartment_name
  - title: IAM
    variables:
      - break_glass_user_email_list
      - show_extra_iam_vars
      - key_id
      - vault_id
  - title: VCN
    variables:
      - vcn_cidr_block
      - vcn_dns_label
      - public_subnet_cidr_block
      - public_subnet_dns_label
      - private_subnet_cidr_blocks
      - private_subnet_dns_labels
      - database_subnet_cidr_blocks
      - database_subnet_dns_labels
      - shared_service_subnet_cidr_block
      - shared_service_subnet_dns_label
      - ingress_rules_map
      - egress_rules_map
  - title: Budget
    variables:
      - budget_alerting
      - budget_amount
      - budget_alert_rule_threshold
      - budget_alert_rule_recipients
      - budget_alert_rule_message
  - title: Security
    variables:
      - is_flow_log_enabled
      - retention_rule_duration_time_amount
      - is_cloud_guard_enabled
      - show_extra_security_vars
      - host_scan_recipe_agent_settings_scan_level
      - host_scan_recipe_port_settings_scan_level
      - agent_cis_benchmark_settings_scan_level
      - vss_scan_schedule
  - title: Bastion
    variables:
      - bastion_client_cidr_block_allow_list
      - bastion_subnet_cidr_block
  - title: DRG (Dynamic Routing Gateways)
    variables:
      - use_ipsec_drg
      - cpe_ip_address
      - ip_sec_connection_static_routes
      - use_fastconnect_drg
      - virtual_circuit_bandwidth_shape
      - provider_service_key_name
      - virtual_circuit_cross_connect_mappings_customer_bgp_peering_ip
      - virtual_circuit_cross_connect_mappings_oracle_bgp_peering_ip
      - virtual_circuit_cross_connect_mappings_customer_secondary_bgp_peering_ip
      - virtual_circuit_cross_connect_mappings_oracle_secondary_bgp_peering_ip
      - fastconnect_provider
      - virtual_circuit_customer_asn
      - fastconnect_routing_policy

variables:
  #Provider Variables
  api_fingerprint:
    type: string
    description: The fingerprint of API
    default: "Value not required in Oracle Resource Manager."
    title: Api Fingerprint
  api_private_key_path:
    type: string
    description: The local path to the API private key
    default: "Value not required in Oracle Resource Manager."
    title: Api Private Key Path
  region:
    type: string
    description: the OCI region
    title: Region
  tenancy_ocid:
    type: string
    description: The OCID of tenancy
    title: Tenancy OCID
  current_user_ocid:
    type: string
    description: OCID of the current user
    title: Current User OCID

  # Tagging
  tag_cost_center:
    type: string
    description: CostCenter tag value
    required: true
    title: Tag Cost Center
  tag_geo_location:
    type: string
    description: GeoLocation tag value
    required: true
    title: Tag Geo Location

  # Compartments
  show_extra_compartment_names:
    type: boolean
    default: false
    required: false
    title: Override default compartment names
  parent_compartment_name:
    type: string
    description: Name of the top level / parent compartment
    required: true
    title: Parent Compartment Name
  workload_compartment_names:
    type: array
    items:
      type: string
    description: List of application workload compartment names
    required: true
    title: Workload Compartment Names
  network_compartment_name:
    type: string
    visible: show_extra_compartment_names
    description: Name of the top level network compartment
    required: true 
    title: Network Compartment Name
  security_compartment_name:
    type: string
    visible: show_extra_compartment_names
    description: Name of the top level security compartment
    required: true 
    title: Security Compartment Name
  common_infra_compartment_name:
    type: string
    visible: show_extra_compartment_names
    description: Name of the top level common infrastructure compartment
    required: true 
    title: Common Infra Compartment Name
  applications_compartment_name:
    type: string
    visible: show_extra_compartment_names
    description: Name of the top level application compartment
    required: true 
    title: Applications Compartment Name

  # IAM
  break_glass_user_email_list:
    type: array
    items:
      type: string
      pattern: ^[^\s@]+@([^\s@.,]+\.)+[^\s@.,]{2,}$
    description:
      Unique list of break glass user email addresses that do not exist
      in the tenancy
    required: true
    title: Break Glass User Email List
  show_extra_iam_vars:
    type: boolean
    description: Show security policy variables. If you already have a vault and encryption key provisioned.
    required: false
    title: Show Security Policy Variables
  key_id:
    type: string
    description: Encryption key OCID for security admin policy
    required: false
    title: Key Id
    visible: show_extra_iam_vars
  vault_id:
    type: string
    description: Vault OCID for security admin policy
    required: false
    title: Vault Id
    visible: show_extra_iam_vars

  # VCN
  vcn_cidr_block:
    type: string
    description: Primary VCN CIDR Block
    required: false
    title: VCN CIDR Block
  vcn_dns_label:
    type: string
    description: VCN DNS Label
    required: true
    title: VCN DNS Label
  private_subnet_cidr_blocks:
    type: array
    items:
      type: string
      # pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}($|(16|24))$
    description: List of Private Subnet CIDR Block (one per workload)
    required: true
    title: Private Subnet CIDR Blocks
  private_subnet_dns_labels:
    type: array
    items:
      type: string
    description: List of Private Subnet DNS Label (one per workload)
    required: true
    title: Private Subnet DNS Labels
  public_subnet_cidr_block:
    type: string
    description: Public Subnet CIDR Block
    required: true
    title: Public Subnet CIDR Block
  public_subnet_dns_label:
    type: string
    description: Public Subnet DNS Label
    required: true
    title: Public Subnet DNS Label
  database_subnet_cidr_blocks:
    type: array
    items:
      type: string
      # pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}($|(16|24))$
    description: List of Database Subnet CIDR Block (one per workload)
    required: true
    title: Database Subnet CIDR Blocks
  database_subnet_dns_labels:
    type: array
    items:
      type: string
    description: List of Database Subnet DNS Label (one per workload)
    required: true
    title: Database Subnet DNS Labels
  egress_rules_map:
    type: text
    description: "[Workload Security List] Egress Rules Map"
    default: "{
      \n\t\"default\" = {
      \n\t\tegress_security_rules_tcp_options_destination_port_range_max = 65535
      \n\t\tegress_security_rules_tcp_options_destination_port_range_min = 1
      \n\t\tegress_security_rules_tcp_options_source_port_range_max      = 65535
      \n\t\tegress_security_rules_tcp_options_source_port_range_min      = 1
      \n\t}
      \n}"
    required: false
    title: Egress Rules Map
    multiline: true
  ingress_rules_map:
    type: text
    description: "[Workload Security List] Ingress Rules Map"
    default: "{
      \n\t\"default\" = {
      \n\t\tingress_security_rules_tcp_options_destination_port_range_max = 65535
      \n\t\tingress_security_rules_tcp_options_destination_port_range_min = 1
      \n\t\tingress_security_rules_tcp_options_source_port_range_max      = 65535
      \n\t\tingress_security_rules_tcp_options_source_port_range_min      = 1
      \n\t}
      \n}"
    required: false
    title: Ingress Rules Map
    multiline: true
  shared_service_subnet_cidr_block:
    type: string
    description: Shared Service Subnet CIDR Block
    required: true
    title: Shared Service Subnet CIDR Block
  shared_service_subnet_dns_label:
    type: string
    description: Shared Service Subnet DNS Label
    required: true
    title: Shared Service Subnet DNS Label

  # Budget
  budget_alerting:
    type: boolean
    description: Set to true to enable budget alerting
    required: true
    title: Budget Alerting
  budget_alert_rule_message:
    type: string
    visible: budget_alerting
    description:
      "(Optional if using budget alerts): The alert message for budget
      alerts."
    required: true
    title: Budget Alert Rule Message
  budget_alert_rule_recipients:
    type: string
    visible: budget_alerting
    description:
      "(Required if using budget alerts): Target email address for budget
      alerts"
    required: true
    title: Budget Alert Rule Recipients
    pattern: ^([^\s@]+@([^\s@.,]+\.)+[^\s@.,]{2,})?$
  budget_alert_rule_threshold:
    type: string
    visible: budget_alerting
    description:
      "(Required if using budget alerts): The target spending threshold
      for the budget"
    default: null
    title: Budget Alert Rule Threshold
  budget_amount:
    type: string
    visible: budget_alerting
    description:
      "(Required if using budget alerts): The amount of the budget expressed
      as a number in the currency of the customer's rate card."
    required: true
    title: Budget Amount

  # Security
  is_flow_log_enabled:
    type: boolean
    description: "Enable or Disable VCN Flow Logs"
    required: false
    title: Enable VCN Flow Logs?
  retention_rule_duration_time_amount:
    type: string
    description: Number of days to retain Audit Logs
    required: true
    title: Audit Log Retention Rule Duration Time Amount
  is_cloud_guard_enabled:
    type: boolean 
    description: the status of the Cloud Guard tenant (ENABLED if true or DISABLED if false)
    required: true
    title: Enable Cloud Guard?
  show_extra_security_vars:
    type: boolean
    description: Show advanced Cloud Guard variables
    required: false
    title: Show Advanced Cloud Guard Variables
  agent_cis_benchmark_settings_scan_level:
    type: enum
    enum:
      - "NONE"
      - "LIGHTWEIGHT"
      - "MEDIUM"
      - "STRICT"
    description: Agent bechamrking settings scan level
    required: false
    title: Agent Cis Benchmark Settings Scan Level
    visible: show_extra_security_vars
  host_scan_recipe_agent_settings_scan_level:
    type: enum
    enum:
      - "NONE"
      - "STANDARD"
    description: Vulnerability scanning service agent scan level
    required: false
    title: Host Scan Recipe Agent Settings Scan Level
    visible: show_extra_security_vars
  host_scan_recipe_port_settings_scan_level:
    type: enum
    enum:
      - "NONE"
      - "LIGHT"
      - "STANDARD"
    description: Vulnerability scanning service port scan level
    required: false
    title: Host Scan Recipe Port Settings Scan Level
    visible: show_extra_security_vars
  vss_scan_schedule:
    type: enum
    enum:
      - "DAILY"
      - "WEEKLY"
    description: Vulnerability scanning service scan schedule
    required: false
    title: Vss Scan Schedule
    visible: show_extra_security_vars

  # Bastion
  bastion_client_cidr_block_allow_list:
    type: array
    items:
      type: string
    description:
      A list of address ranges in CIDR notation that bastion is allowed
      to connect
    required: true
    title: Bastion Client CIDR Block Allow List
  bastion_subnet_cidr_block:
    type: string
    description: CIDR Block for bastion subnet
    required: true
    title: Bastion Subnet CIDR Block

  # DRG Values
  use_ipsec_drg:
    type: boolean
    description: Choose whether or not to use an IPsec based DRG.
    required: true
    title: Use IPsec DRG?
  cpe_ip_address:
    type: string
    visible: use_ipsec_drg
    required: true
    title: CPE IP Address
  ip_sec_connection_static_routes:
    visible: use_ipsec_drg
    type: array
    items:
      type: string
    required: true
    title: IPsec Connection Static Routes
  use_fastconnect_drg:
    type: boolean
    description: Choose whether or not to use FastConnect
    required: true
    title: Use FastConnect?
  virtual_circuit_bandwidth_shape:
    type: string
    visible: use_fastconnect_drg
    required: true
    title: Virtual Circuit Bandwidth Shape
  provider_service_key_name:
    type: string 
    visible: use_fastconnect_drg
    required: true
    title: Provider Service Key Name
  virtual_circuit_cross_connect_mappings_customer_bgp_peering_ip:
    type: string
    visible: use_fastconnect_drg
    required: true
    title: Virtual Circuit Cross Connect Mappings - Customer BGP peering IP
  virtual_circuit_cross_connect_mappings_oracle_bgp_peering_ip:
    type: string
    visible: use_fastconnect_drg
    required: true
    title: Virtual Circuit Cross Connect Mappings - Oracle BPG Peering IP
  virtual_circuit_cross_connect_mappings_customer_secondary_bgp_peering_ip:
    type: string
    visible: use_fastconnect_drg
    required: true
    title: Virtual Circuit Cross Connect Mappings - Customer Secondary BGP Peering IP
  virtual_circuit_cross_connect_mappings_oracle_secondary_bgp_peering_ip:
    type: string
    visible: use_fastconnect_drg
    required: true
    title: Virtual Circuit Cross Connect Mappings - Oracle Secondary BGP Peering IP
  fastconnect_provider:
    type: enum
    enum:
      - AT&T
      - Microsoft Azure
      - Megaport
      - QTS
      - CEintro
      - Cologix
      - CoreSite
      - Digitial Realty
      - EdgeConneX
      - Epsilon
      - Equinix
      - InterCloud
      - Lumen
      - Neutrona
      - OMCS
      - OracleL2ItegDeployment
      - OracleL3ItegDeployment
      - Orange
      - Verizon
      - Zayo 
    visible: use_fastconnect_drg
    required: true
    title: FastConnect Provider
  virtual_circuit_customer_asn:
    type: number
    visible: use_fastconnect_drg
    required: true
    title: Virtual Circuit Customer ASN
  fastconnect_routing_policy:
    type: array
    description: Available FastConnect routing policies:\ ORACLE_SERVICE_NETWORK, REGIONAL, MARKET_LEVEL, GLOBAL
    visible: use_fastconnect_drg
    items:
      type: string 
      pattern: \b(?:ORACLE_SERVICE_NETWORK|REGIONAL|MARKET_LEVEL|GLOBAL)\b
    required: true
    uniqueItems: true
    title: FastConnect Routing Policy
